- hosts: targets
  vars:
    ansible_ssh_username: venues
    ansible_ssh_password: 123456
  tasks:
    - name: change password
      user: name={{ item.username}} password={{ item.chpass | password_hash('sha512') }} update_password=always
      with_items:
        - { name:'venues', chpass:'Metc1309' }